name: concept_maps
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.0+2

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: 0.16.1
  google_fonts: ^3.0.1
  http: ^0.13.5
  zoom_widget: ^2.0.0
  provider: ^6.0.4
  material_floating_search_bar: ^0.3.7
  auto_size_text: ^3.0.0
  flutter_highlight: ^0.7.0
  new_gradient_app_bar: ^0.2.0
  flutter_html: ^2.2.1
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6
  flutter_math_fork: ^0.5.0
  fl_chart: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
 